start: specification

?specification: "Specification" IDENTIFIER "{" repository_decl? start_terminal_decl reference_decl* process+ "}"

reference_decl: "Ref" ELEMENT_TYPE IDENTIFIER "=" reference_value ";"
reference_value: STRING | reference_path

repository_decl: "Repository" "=" STRING ";"

start_terminal_decl: "StartTerminal" "=" "[" IDENTIFIER "]"  ";"

process: "Process"  IDENTIFIER "{" interface_decl?  body_decl? evolution_decl? "}"

interface_decl: "Interface" "{" terminal_decl* port_decl* predicate_decl* elem_declaration* submodel_declaration* "}"
body_decl: "Body" "{" statement* "}"
evolution_decl: "Evolution" "{"  "}"


terminal_decl: "Terminal" DIRECTION  IDENTIFIER ";"
port_decl: "Port" DIRECTION IDENTIFIER port_reference? ";"
port_reference: "=" reference_path


predicate_decl: "Predicate" IDENTIFIER  "->" IDENTIFIER "{" expression "}"

expression: boolean_expression | arithmetic_expression | literal | qualified_identifier | relational_expression | qualified_literal
boolean_expression: BOOLEAN_OPERATOR "(" expression_list ")" |  UNARY_BOOLEAN_OPERATOR "(" expression ")"
relational_expression: RELATIONAL_OPERATOR "(" expression_list ")"
arithmetic_expression: ARITHMETIC_OPERATOR "(" expression_list ")"

reference_path: IDENTIFIER ("." IDENTIFIER)*
qualified_identifier: IDENTIFIER ("." IDENTIFIER)*
literal: NUMBER | STRING | BOOLEAN
qualified_literal: NUMBER "@" IDENTIFIER ":" IDENTIFIER

statement: assignment_stmt | if_stmt | foreach_stmt

elem_declaration: property_declaration | range_declaration | smc_declaration 
property_declaration: PROPERTY IDENTIFIER "= "  NEW PROPERTY "(" STRING "," STRING "," STRING ")" ";"
range_declaration: RANGE IDENTIFIER "= "  NEW  RANGE "(" STRING "," STRING "," STRING "," STRING ")" ";"
smc_declaration: SMC IDENTIFIER "=" NEW SMC  "{" member_list* "}" ";"
submodel_declaration: SUBMODEL IDENTIFIER "=" NEW SUBMODEL  "{" member_list* "}" ";"
member_list: submodel_element ("," submodel_element)*
?submodel_element: elem_declaration | IDENTIFIER 

semantic_ref: IDENTIFIER ":" IDENTIFIER

expression_list: expression ("," expression)*
element_list: expression ("," expression)*


expression_stmt: expression ";"
assignment_stmt: ASSIGNMENT_OPERATOR "(" expression_list ")" ";"
if_stmt: "IF" "(" expression ")" "THEN" statement*"END_IF" ";"
foreach_stmt: "FOREACH" "(" IDENTIFIER "IN" expression ")" "DO" statement* "END_FOREACH" ";"

   

UNARY_BOOLEAN_OPERATOR.20: "not" | "notS"
BOOLEAN_OPERATOR.20: "and" | "andS" | "or" | "orS"
ARITHMETIC_OPERATOR.20: "add" | "addS" | "sub" | "subS" | "mul" | "mulS" | "div" | "divS"
RELATIONAL_OPERATOR.20: "equal" | "equalS" | "less" | "lessS" | "lessE" | "lessES" | "great" | "greatS" | "greatE" | "greatES"
ASSIGNMENT_OPERATOR.20: "assign" | "assignS"
BOOLEAN.10: "True" | "False"
NEW.20 : "new"


ELEMENT_TYPE.10: PROPERTY | RANGE | SMC | SUBMODEL
PROPERTY: "Property"
RANGE: "Range"
SMC: "SMC"
SUBMODEL: "Submodel"

DIRECTION : INPUT | OUTPUT
INPUT: "Input"
OUTPUT: "Output"

IDENTIFIER: /[A-Za-z_][A-Za-z0-9_]*/


%import common.SIGNED_NUMBER -> NUMBER
%import common.ESCAPED_STRING -> STRING
%import common.WS

%ignore WS

%ignore /\/\/[^\r\n]*/
%ignore /\/\*(.|\n)*?\*\//
